### ISSUE TITLE
Link to my website

### ISSUE THREAD

**Issue by franzfilip** [rstropek-teaching/contact-list-quiz-5ahif-franzfilip#1]
Hello Mr. Stropek!

This is my link to my WebAPI: http://csharphomeworkrestapi2017.azurewebsites.net/api/person

You can try all CRUD Operations
Methods where u need an index:
- Get (if you want to get one person with ID)
- Delete 
- Update

**Comment by rstropek** [comment]
@franzfilip Thank you for your homework. You did not implement the Web API exactly as specified in the Swagger spec. Still, congrats for what you have built and that you managed to publish the API in Azure 👍 Your extra point is secured.

**Warning**: You checked in database credentials in GitHub. Everybody could read your code and access your database! **NEVER** check in secrets like usernames, passwords, etc. in a source code repository!

Greetings,
Rainer Stropek.
